### PR TITLE
Adds rounded bricks

### PR DESCRIPTION
**Pull request by benzvan**
New brick type "round" can be rounded on all 4 corners by round_radius
studs.

### CODE REVIEW

**Comment by benzvan** [comment]
Let me know if this appeals to you or if you'd like changes in use. Feel free to change my formatting; the extra whitespace made it easier to see where I could avoid repeating myself.

**Comment by cfinke** [comment]
Very cool!  I noticed that if I try to make a round brick like this:

`
block(
        type="round",
        width=3,
        length=3
    );
`

it still comes out square because I didn't specify a `round_radius`, but I expected it to be circular by default. Can you make it so that if a block is supposed to be round but has no radius specified, it comes out circular? And then add a simple round 3x3 brick to `LEGO Examples.scad`?  This should work:

`
color("white") place(-6, 13) block(
    type="round",
    width=3,
    length=3
);
`

**Comment by benzvan** [comment]
Thanks! i updated so the default is the maximum radius that will make sense. If you create a 3x6 brick, it'll be rounded the same as s 3x3 brick.

(Is there some magic rotation happening in that example file to make the bricks fit? If I change width or length independently, the brick is always bigger on the x axis only.)

**Comment by cfinke** [comment]
> (Is there some magic rotation happening in that example file to make the bricks fit? If I change width or length independently, the brick is always bigger on the x axis only.)

The longest measurement is always the length. This was done to solve some problem that I have forgotten, but it was probably related to code simplicity.

**Comment by cfinke** [comment]
I've merged this changeset in; thanks!

**Pull request merged**
